export const sampleTypes = [
  "Blood sample collection",
  "Urine sample collection",
  "Stool sample collection",
  "Sputum sample collection",
] as const;

export const karachiAreas = [
  "Abbas Town",
  "Abbasi Shaheed",
  "Abdul Rehman Goth",
  "Abdullah Goth",
  "Abidabad",
  "Abu Zar Ghaffari",
  "Abyssinia Lines",
  "Afridi Colony",
  "Agra Taj Colony",
  "Ahsanabad",
  "Aisha Manzil",
  "Akhtar Colony",
  "Al-Asif Square",
  "Al-Falah Society",
  "Al-Hilal Society",
  "Al-Noor Society",
  "Allama Banuri Town",
  "Allama Iqbal Colony",
  "Ancholi",
  "Aram Bagh",
  "Askari 4",
  "Askari 5",
  "Azam Basti",
  "Azizabad",
  "Baba Island",
  "Badar Commercial",
  "Baghdadi",
  "Bahadurabad",
  "Baldia Colony",
  "Baldia Town",
  "Baloch Colony",
  "Baloch Goth",
  "Banaras Colony",
  "Bandhani Colony",
  "Bath Island",
  "Bhim Pura",
  "Bhittai Colony",
  "Bhutta Village",
  "Bihar Colony",
  "Bilal Colony",
  "Boat Basin",
  "Bohra Pir",
  "Buffer Zone",
  "Burns Road",
  "C-Area",
  "Cantt Station",
  "Cattle Colony",
  "Central Jacob Lines",
  "Chanesar Goth",
  "City Railway Colony",
  "Civil Lines",
  "Clifton",
  "Clifton Block 1",
  "Clifton Block 2",
  "Clifton Block 3",
  "Clifton Block 4",
  "Clifton Block 5",
  "Clifton Block 6",
  "Clifton Block 7",
  "Clifton Block 8",
  "Clifton Block 9",
  "Clifton Kehkashan",
  "Commercial Area",
  "Dalmia",
  "Darakhshan",
  "Daryaabad",
  "Defence View",
  "Delhi Colony",
  "Delhi Mercantile Society",
  "DHA Phase 1",
  "DHA Phase 2",
  "DHA Phase 3",
  "DHA Phase 4",
  "DHA Phase 5",
  "DHA Phase 6",
  "DHA Phase 7",
  "DHA Phase 8",
  "DHA Phase 8 Extension",
  "Drigh Colony",
  "Essa Nagri",
  "Falaknaz Area",
  "Faisal Colony",
  "Farooq-e-Azam",
  "Federal B Area",
  "Federal B Area Block 1",
  "Federal B Area Block 2",
  "Federal B Area Block 3",
  "Federal B Area Block 4",
  "Federal B Area Block 5",
  "Federal B Area Block 6",
  "Federal B Area Block 7",
  "Federal B Area Block 8",
  "Federal B Area Block 9",
  "Federal B Area Block 10",
  "Federal B Area Block 11",
  "Federal B Area Block 12",
  "Federal B Area Block 13",
  "Federal B Area Block 14",
  "Federal B Area Block 15",
  "Federal B Area Block 16",
  "Federal B Area Block 17",
  "Federal B Area Block 18",
  "Federal B Area Block 19",
  "Federal B Area Block 20",
  "Federal B Area Block 21",
  "Federal B Area Block 22",
  "Firdous Colony",
  "Frere Town",
  "Gabol Colony",
  "Gadap Town",
  "Garden East",
  "Garden West",
  "Gazdarabad",
  "Ghanchi Para",
  "Gharibabad",
  "Gizri",
  "Godhra",
  "Golimar",
  "Gulbahar",
  "Gulberg",
  "Gulistan Colony",
  "Gulistan-e-Jauhar",
  "Gulistan-e-Jauhar Block 1",
  "Gulistan-e-Jauhar Block 2",
  "Gulistan-e-Jauhar Block 3",
  "Gulistan-e-Jauhar Block 4",
  "Gulistan-e-Jauhar Block 5",
  "Gulistan-e-Jauhar Block 6",
  "Gulistan-e-Jauhar Block 7",
  "Gulistan-e-Jauhar Block 8",
  "Gulistan-e-Jauhar Block 9",
  "Gulistan-e-Jauhar Block 10",
  "Gulistan-e-Jauhar Block 11",
  "Gulistan-e-Jauhar Block 12",
  "Gulistan-e-Jauhar Block 13",
  "Gulistan-e-Jauhar Block 14",
  "Gulistan-e-Jauhar Block 15",
  "Gulistan-e-Jauhar Block 16",
  "Gulistan-e-Jauhar Block 17",
  "Gulistan-e-Jauhar Block 18",
  "Gulistan-e-Jauhar Block 19",
  "Gulistan-e-Jauhar Block 20",
  "Gulshan-e-Ghazi",
  "Gulshan-e-Hadeed",
  "Gulshan-e-Iqbal",
  "Gulshan-e-Iqbal Block 1",
  "Gulshan-e-Iqbal Block 2",
  "Gulshan-e-Iqbal Block 3",
  "Gulshan-e-Iqbal Block 4",
  "Gulshan-e-Iqbal Block 5",
  "Gulshan-e-Iqbal Block 6",
  "Gulshan-e-Iqbal Block 7",
  "Gulshan-e-Iqbal Block 8",
  "Gulshan-e-Iqbal Block 9",
  "Gulshan-e-Iqbal Block 10",
  "Gulshan-e-Iqbal Block 11",
  "Gulshan-e-Iqbal Block 12",
  "Gulshan-e-Iqbal Block 13",
  "Gulshan-e-Iqbal Block 14",
  "Gulshan-e-Iqbal Block 15",
  "Gulshan-e-Iqbal Block 16",
  "Gulshan-e-Iqbal Block 17",
  "Gulshan-e-Iqbal Block 18",
  "Gulshan-e-Iqbal Block 19",
  "Gulshan-e-Iqbal Block 20",
  "Gulshan-e-Maymar",
  "Gulshan-e-Saeed",
  "Gulshan-e-Zia",
  "Gulzar-e-Hijri",
  "Hadi Market",
  "Hakim Ahsan",
  "Hasan Lashkari Village",
  "Hijrat Colony",
  "Hussainabad",
  "Hyderi",
  "Ibrahim Hyderi",
  "Ilyas Goth",
  "Iqbal Baloch Colony",
  "Islamia Colony",
  "Ittehad Town",
  "Jail Road",
  "Jamil Colony",
  "Jamshed Quarters",
  "Jodia Bazaar",
  "Johar Complex",
  "Jutland Lines",
  "K.D.A. Scheme 1",
  "K.D.A. Scheme 33",
  "Kala Pul",
  "Kalakot",
  "Kalri",
  "Karimabad",
  "Karsaz",
  "Kathore",
  "Kausar Niazi Colony",
  "KDA Officers Society",
  "KDA Scheme 33",
  "Keamari",
  "Kehkashan",
  "Khadda Memon Society",
  "Khamiso Goth",
  "Kharadar",
  "Khawaja Ajmer Nagri",
  "Khuda Ki Basti",
  "Kiran Hospital Area",
  "Korangi",
  "Korangi 1",
  "Korangi 2",
  "Korangi 2.5",
  "Korangi 3",
  "Korangi 3.5",
  "Korangi 4",
  "Korangi 5",
  "Korangi 6",
  "Korangi Creek",
  "Korangi Industrial Area",
  "Landhi",
  "Landhi 1",
  "Landhi 2",
  "Landhi 3",
  "Landhi 4",
  "Landhi 5",
  "Landhi 6",
  "Landhi Industrial Area",
  "Lasbela",
  "Liaquatabad",
  "Liaquatabad C-Area",
  "Lines Area",
  "Lyari",
  "Madina Colony",
  "Malir",
  "Malir Cantonment",
  "Malir City",
  "Malir Colony",
  "Malir Halt",
  "Manghopir",
  "Manzoor Colony",
  "Maripur",
  "Martin Quarters",
  "Mehmoodabad",
  "Metroville",
  "Millat Nagar",
  "Model Colony",
  "Mominabad",
  "Moosa Colony",
  "Mujahid Colony",
  "Muslimabad",
  "Mustafaabad",
  "Nanak Wara",
  "Naseerabad",
  "Naval Colony",
  "Nazimabad",
  "Nazimabad 1",
  "Nazimabad 2",
  "Nazimabad 3",
  "Nazimabad 4",
  "Nazimabad 5",
  "New Karachi",
  "New Karachi Sector 5-A",
  "New Karachi Sector 5-C",
  "New Karachi Sector 5-D",
  "New Karachi Sector 11-D",
  "New M.A. Jinnah Road",
  "New Rizvia Society",
  "New Saeedabad",
  "North Karachi",
  "North Karachi Sector 5-A",
  "North Karachi Sector 5-B",
  "North Karachi Sector 7-D",
  "North Karachi Sector 11-A",
  "North Karachi Sector 11-B",
  "North Karachi Sector 11-C",
  "North Karachi Sector 11-E",
  "North Nazimabad",
  "North Nazimabad Block A",
  "North Nazimabad Block B",
  "North Nazimabad Block C",
  "North Nazimabad Block D",
  "North Nazimabad Block E",
  "North Nazimabad Block F",
  "North Nazimabad Block G",
  "North Nazimabad Block H",
  "North Nazimabad Block I",
  "North Nazimabad Block J",
  "North Nazimabad Block K",
  "North Nazimabad Block L",
  "North Nazimabad Block M",
  "North Nazimabad Block N",
  "North Nazimabad Block O",
  "North Nazimabad Block P",
  "North Nazimabad Block Q",
  "North Nazimabad Block R",
  "North Nazimabad Block S",
  "North Nazimabad Block T",
  "Northern Bypass",
  "Old City Area",
  "Orangi Town",
  "Orangi Town Sector 4",
  "Orangi Town Sector 5",
  "Orangi Town Sector 7",
  "Orangi Town Sector 8",
  "Orangi Town Sector 10",
  "Orangi Town Sector 11",
  "Other / Not listed",
  "Pahar Ganj",
  "Pahlwan Goth",
  "Pakistan Chowk",
  "Pakistan Quarters",
  "Paposh Nagar",
  "Patel Para",
  "PECHS",
  "PECHS Block 2",
  "PECHS Block 3",
  "PECHS Block 6",
  "PIB Colony",
  "Punjab Colony",
  "Qasba Colony",
  "Quaidabad",
  "Rafa-e-Aam Society",
  "Ragiwara",
  "Ranchore Line",
  "Rangiwara",
  "Rashid Minhas Road",
  "Rexer Lane",
  "Rizvia Society",
  "Saadi Town",
  "Saddar",
  "Safoora Goth",
  "Sakhi Hassan",
  "Samanabad",
  "Saudabad",
  "Scheme 33",
  "Shadman Town",
  "Shafiq Mill Colony",
  "Shah Baig Lane",
  "Shah Faisal Colony",
  "Shah Latif Town",
  "Shah Nawaz Bhutto Colony",
  "Shanti Nagar",
  "Sharafabad",
  "Sharifabad",
  "Sher Shah",
  "Shershah Colony",
  "Shireen Jinnah Colony",
  "Singo Lane",
  "Sir Syed Colony",
  "Sohrab Goth",
  "Soldier Bazaar",
  "Steel Town",
  "Sultanabad",
  "Super Highway",
  "Surjani Town",
  "Taimooria",
  "Tariq Road",
  "Teen Hatti",
  "Tipu Sultan Road",
  "University Road",
  "Water Pump",
  "Yaseenabad",
  "Zaman Town",
] as const;

export const timeSlots = Array.from({ length: 27 }, (_, index) => {
  const totalMinutes = 9 * 60 + index * 30;
  const hour24 = Math.floor(totalMinutes / 60);
  const minutes = totalMinutes % 60;
  const hour12 = hour24 % 12 || 12;
  const period = hour24 >= 12 ? "PM" : "AM";

  return `${hour12}:${minutes.toString().padStart(2, "0")} ${period}`;
});

export function getTimeSlotMinutes(timeSlot: string) {
  const match = /^(\d{1,2}):(\d{2}) (AM|PM)$/.exec(timeSlot);

  if (!match) {
    return -1;
  }

  const [, hourValue, minuteValue, period] = match;
  const hour12 = Number(hourValue);
  const minutes = Number(minuteValue);

  if (hour12 < 1 || hour12 > 12 || minutes < 0 || minutes > 59) {
    return -1;
  }

  const hour24 =
    period === "AM" ? hour12 % 12 : hour12 === 12 ? 12 : hour12 + 12;

  return hour24 * 60 + minutes;
}
